## numpy.array

In [25]:
import numpy as np
d = np.array([[1,2],[3,4]])
d.ndim , d.shape 

(2, (2, 2))

In [34]:
a = np.array([[[1,2,3,5,8],
               [4,5,9,5,8],
               [3,2,3,5,8]],
              [[3,4,5,5,8],
               [2,7,9,5,8],
               [3,2,3,5,8]]
             ])

In [35]:
len(a) , len(a[0]) ,len(a[0][0]) ,a.shape

(2, 3, 5, (2, 3, 5))

In [21]:
a.ndim

3

In [27]:
c =np.array([1,2,3,5])
c.ndim , c.shape

(1, (4,))

In [28]:
import numpy as np
d = np.array([[1,2],[3,4]])
d*5

array([[ 5, 10],
       [15, 20]])

In [31]:
d**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [32]:
np.zeros(4)

array([0., 0., 0., 0.])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.log(2)

0.6931471805599453

In [43]:
np.logspace(0, 100 , 4)

array([1.00000000e+000, 2.15443469e+033, 4.64158883e+066, 1.00000000e+100])

In [45]:
arr = np.array(range(0,20))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
arr.reshape(2,10)

ValueError: cannot reshape array of size 20 into shape (2,5)

In [57]:
arr.reshape(10 ,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [60]:
arr_3d = arr.reshape(2,2,-1)
arr_3d


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
a = np.ones((3,4))
a*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [68]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [69]:
a  = np.array(range(1,6))

In [70]:
a

array([1, 2, 3, 4, 5])

In [71]:
a[np.newaxis]

array([[1, 2, 3, 4, 5]])

In [79]:
a1 = np.ones((3,4)) 
a2 = np.zeros((3,4)) 
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.hstack([a1, a2])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [76]:
np.vstack([a1, a2])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.stack([a1, a2])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
arr = np.array([[5,6,7,8,9], [0,1,2,3,4]])
arr

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [82]:
arr.max()

9

In [83]:
arr.min()

0

In [84]:
arr.mean()

4.5

In [86]:
arr.max(axis=0)

array([5, 6, 7, 8, 9])

In [87]:
arr.min(axis=0)

array([0, 1, 2, 3, 4])

In [88]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [89]:
arr.max(axis=1)

array([9, 4])

In [90]:
arr.min(axis=1)

array([5, 0])

In [91]:
arr.mean(axis=1)

array([7., 2.])

In [93]:
arr = np.array([[[5,6,7,8,9], [0,1,2,3,4]],
              [[100,20,7,8,9], [30,1,45,3,4]]]
              )
arr.max(axis=2)

array([[  9,   4],
       [100,  45]])

In [94]:
arr.min(axis=2)

array([[5, 0],
       [7, 1]])

In [95]:
arr.mean(axis=2)

array([[ 7. ,  2. ],
       [28.8, 16.6]])

In [96]:
arr.max(axis=0)

array([[100,  20,   7,   8,   9],
       [ 30,   1,  45,   3,   4]])

In [97]:
arr.min(axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [98]:
arr.mean(axis=0)

array([[52.5, 13. ,  7. ,  8. ,  9. ],
       [15. ,  1. , 23.5,  3. ,  4. ]])

In [99]:
arr3 = [[[5,6,7,8,9], [0,1,2,3,4]],
              [[100,20,7,8,9], [30,1,45,3,4]]]

In [100]:
arr3

[[[5, 6, 7, 8, 9], [0, 1, 2, 3, 4]], [[100, 20, 7, 8, 9], [30, 1, 45, 3, 4]]]

In [101]:
arr3.mean(axis=0)

AttributeError: 'list' object has no attribute 'mean'

In [105]:
arr4 = np.array([[5,211,7,8,9],
                 [0,20,2,3,4]])
arr4.max(axis=0)

array([  5, 211,   7,   8,   9])

In [120]:
arr4.max(axis=1)

array([211,  20])

In [127]:
np.random
np.random.randint(1, 100)

70

In [124]:
np.random.rand(5)

array([0.81216873, 0.47997717, 0.3927848 , 0.83607876, 0.33739616])

In [130]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.random.shuffle(x)
print(x)

[8 1 7 4 9 3 0 6 5 2]


In [140]:
x = np.random.choice(46, 6, replace=False)
x

array([43, 40, 35, 16, 12, 38])

In [141]:
np.random.choice(4, 3, replace=False, p=[0.4, 0.2, 0, 0.4]) 

array([0, 3, 1])

In [144]:
f = np.random.rand(3,4)
f[f>0.3] =3
f

array([[3.        , 0.0191932 , 3.        , 3.        ],
       [0.29007761, 3.        , 3.        , 0.13547406],
       [0.29828233, 3.        , 3.        , 3.        ]])

In [147]:
x = np. linspace(1, 11, 20)
x

array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ])

In [148]:
np.ceil(x)  

array([ 1.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,  8.,
        8.,  9.,  9., 10., 10., 11., 11.])